# fly.toml app configuration file generated for lt-otel-collector on 2024-04-09T11:42:11+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lt-otel-collector'
primary_region = 'lhr'

[[services]]
  internal_port = 4317
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services.ports]]
  handlers = []
  port = 80
  force_https = false

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
