[workspace]
resolver = "2"
members = [
  "shared_models",
  "backend",
  "frontend",
  "website",
]

[workspace.package]
version = "0.7.1-alpha.1"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
