[workspace]
resolver = "2"

[workspace.package]
version = "0.5.0"
edition = "2021"
members = [
  "shared_models",
  "backend",
  "frontend",
  "website",
]

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
