# fly.toml app configuration file generated for unload on 2023-11-28T12:24:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "unload-dev"
primary_region = "lhr"

[build]

[processes]
  app = "unload"
  cron = '"supercronic /etc/crontab"'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  UNLOAD_DATABASE_URL = "sqlite:/mnt/unload_data/unload.db"
  UNLOAD_SERVER_ADDRESS = "0.0.0.0:8080"
  UNLOAD_APP_SERVE_DIR = "/var/www/app"
  UNLOAD_WEBSITE_SERVE_DIR = "/var/www/website"
  UNLOAD_LOG = "unload=trace,[request{}]=trace,sqlx::query=trace"
  UNLOAD_OTLP_ENDPOINT = "http://lt-otel-collector.flycast"
  UNLOAD_ENVIRONMENT = "development"

[mounts]
  source="unload_data"
  destination="/mnt/unload_data"
