[package]
name = "website"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.5.1"
dioxus-ssr = "0.5.1"
fs_extra = "1.3.0"
