name: Publish release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  TAG: ${{ github.ref_name }}

jobs:
  publish-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: docker/setup-buildx-action@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: publish-release-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install toml-cli
      - run: test "$(toml get -r Cargo.toml workspace.package.version)" = "${TAG#v}"
      - run: fly deploy --local-only --config fly.prod.toml --image-label "${TAG#v}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
