name: Tests
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install sqlx-cli --no-default-features --features sqlite
      - run: just test
